In [1]:
import cv2

LOGO_IMAGE = cv2.imread('C:/Users/bettmensch/Pictures/bettmensch.ai/logo_transparent.png')

In [3]:
LOGO_IMAGE.shape

(460, 378, 3)

In [9]:
cv2.imshow('image',LOGO_IMAGE)
cv2.waitKey(0)

-1

In [22]:
LOGO_IMAGE[:10,:13,0]

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 234, 234],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 234, 234, 234, 234],
       [255, 255, 255, 255, 255, 255, 255, 255, 234, 234, 234, 234, 234],
       [255, 255, 255, 255, 255, 255, 255, 234, 234, 234, 234, 234, 234],
       [255, 255, 255, 255, 255, 234, 234, 234, 234, 234, 234, 234, 234],
       [255, 255, 255, 255, 255, 234, 234, 234, 234, 234, 234, 234, 234],
       [255, 255, 255, 255, 234, 234, 234, 234, 234, 234, 234, 234, 234],
       [255, 255, 255, 234, 234, 234, 234, 234, 234, 234, 234, 234, 234]],
      dtype=uint8)

In [23]:
LOGO_IMAGE[:10,:13,1]

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 217, 217],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 217, 217, 217, 217],
       [255, 255, 255, 255, 255, 255, 255, 255, 217, 217, 217, 217, 217],
       [255, 255, 255, 255, 255, 255, 255, 217, 217, 217, 217, 217, 217],
       [255, 255, 255, 255, 255, 217, 217, 217, 217, 217, 217, 217, 217],
       [255, 255, 255, 255, 255, 217, 217, 217, 217, 217, 217, 217, 217],
       [255, 255, 255, 255, 217, 217, 217, 217, 217, 217, 217, 217, 217],
       [255, 255, 255, 217, 217, 217, 217, 217, 217, 217, 217, 217, 217]],
      dtype=uint8)

In [24]:
LOGO_IMAGE[:10,:13,2]

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 153, 153],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 153, 153, 153, 153],
       [255, 255, 255, 255, 255, 255, 255, 255, 153, 153, 153, 153, 153],
       [255, 255, 255, 255, 255, 255, 255, 153, 153, 153, 153, 153, 153],
       [255, 255, 255, 255, 255, 153, 153, 153, 153, 153, 153, 153, 153],
       [255, 255, 255, 255, 255, 153, 153, 153, 153, 153, 153, 153, 153],
       [255, 255, 255, 255, 153, 153, 153, 153, 153, 153, 153, 153, 153],
       [255, 255, 255, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153]],
      dtype=uint8)

In [42]:
import numpy as np
MASK = np.expand_dims((LOGO_IMAGE != 255).any(-1).astype(int) * 255,-1)
MASK.shape

(460, 378, 1)

In [44]:
MASK[:30,:13,0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255, 255, 255],
       [  0,   0,   0,   0,   0,   0,   0,   0, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0,   0,   0,   0, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0, 255, 255, 255, 255, 255, 

In [45]:
import numpy as np
LOGO_IMAGE_W_MASK = np.concatenate([LOGO_IMAGE,MASK],-1)

In [46]:
LOGO_IMAGE_W_MASK.shape

(460, 378, 4)

In [48]:
LOGO_IMAGE_W_MASK[:10,:10,0],LOGO_IMAGE_W_MASK[:10,:10,1],LOGO_IMAGE_W_MASK[:10,:10,2],LOGO_IMAGE_W_MASK[:10,:10,3]

(array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 234],
        [255, 255, 255, 255, 255, 255, 255, 255, 234, 234],
        [255, 255, 255, 255, 255, 255, 255, 234, 234, 234],
        [255, 255, 255, 255, 255, 234, 234, 234, 234, 234],
        [255, 255, 255, 255, 255, 234, 234, 234, 234, 234],
        [255, 255, 255, 255, 234, 234, 234, 234, 234, 234],
        [255, 255, 255, 234, 234, 234, 234, 234, 234, 234]]),
 array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 217],
        [255, 255, 255, 255, 255, 255, 255, 255, 217, 217],
        [255, 255, 255, 255, 255, 255, 255, 217, 217, 217],
        [255, 255, 255, 255, 255, 217,

In [1]:
from rembg import remove

C:\Users\bettmensch\AppData\Roaming\Python\Python311\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (8.1). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
